### ISSUE TITLE
Check state before rerender

### ISSUE THREAD

**Issue by xiki808** [albertopumar/lit-element-redux#7]
I find this solution very interesting! I would like to switch to this and have a more lit related redux solution. For my redux implementation I have followed this setup: https://vaadin.com/learn/tutorials/lit-element/state-management-with-redux

For a component that is connected, it provides a function `stateChanged` which I find very useful as there I can do checks using other props from the same component, and if needed, I update my component's 'state' property and that will cause a rerender.

When trying to switch to this package, I realize that I cannot do this within the component. Not even the `hasChanged` function is triggered on the mapped property - which is not enough either for me, as I cannot access other props from the same component.

Am I missing something? Is there a way how I can receive the state changed, and check it before, in order to let me decide when I want a rerender?

**Comment by albertopumar** [comment]
Sorry for the big delay, I wans't sure about the tracktion of this library. I will start maintainig this library again.

Can you explain a bit more your problem? Right now, I don't see the point of having an old state in the component while updating the store.

**Comment by albertopumar** [comment]
Feel free to reopen it with more information!
